#!/usr/bin/env bash
### chief-zomg -- rely, lock and vote all in one!
### Usage: chief zomg <ds-chief> <slate>
###
### rely, lock and vote all in one!
set -e

chief=$(seth --to-address "$1")
echo "--- Approving chief to operate on MKR ---"
chief rely-gov "$chief"
sleep 10
echo "--- Locking MKR ---"
chief lock-gov "$chief"
sleep 10
echo "--- Voting on slate ---"
chief vote "$chief" "$2"