#!/usr/bin/env bash
### chief -- governance voting
### Usage: chief [<options>] <command> [<args>]
###    or: chief <command> --help
###
### Interact with a ds-chief

OPTS="chief [<options>] <command> [<args>]
chief <command> --help
--
  Options:
auto                 run chief bot in auto mode (no user interaction)
C,config=file        configuration file
S,spread=percent     minimum percent deviation to update (default: 1)
I,interval=seconds   seconds to wait between checks (default: 60)
R,resend=seconds     seconds to wait before resending tx (default: 90)

  Gas options:
gas-start=gas        starting gas price per tx in wei
gas-inc=gas          amount to increment gas price per tx in wei
gas-max=gas          maximum gas price to pay per tx in wei

  Miscellaneous:
verbose              output extra information (useful for debugging)
"

set -e

if [[ $2 = --help ]]; then
  exec "${0##*/}" help "$1"
elif [[ $1 = -* ]] && command -v "${0##*/}-$1" &>/dev/null; then
  exec "${0##*/}-$1" "${@:2}"
fi

eval "$(git rev-parse --parseopt -- "$@" <<<"$OPTS" || echo exit $?)"

while [[ $1 ]]; do
  case $1 in
    --)              shift; break;;
    
       --auto)              export chief_AUTO=yes;;
       --verbose)           export chief_VERBOSE=yes;;

    -C|--config)     shift; export chief_CONF=$1;;

    -S|--spread)     shift; export chief_SPREAD=$1;;

    -I|--interval)   shift; export chief_INTERVAL_SECONDS=$1;;
    -R|--resend)     shift; export chief_WAIT_FOR_RESEND=$1;;

       --gas-start)  shift; export chief_INITIAL_GAS_PRICE=$1;;
       --gas-inc)    shift; export chief_GAS_PRICE_INCREMENT=$1;;
       --gas-max)    shift; export chief_MAX_GAS_PRICE=$1;;

    *) printf "${0##*/}: internal error: %q\\n" "$1"; exit 1
  esac; shift
done

"${0##*/}-${1-help}" "${@:2}"
